# Generated by Django 5.1.3 on 2025-11-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ean",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Código de barras"
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock_min", models.IntegerField(default=0)),
                ("ubicacion", models.CharField(blank=True, max_length=60, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.categoria",
                    ),
                ),
            ],
            options={
                "db_table": "producto",
            },
        ),
    ]
