# Generated by Django 5.1.3 on 2025-11-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ean",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Código de barras"
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "precio",
                    models.PositiveIntegerField(
                        default=0, help_text="Precio de venta en pesos chilenos"
                    ),
                ),
                (
                    "costo",
                    models.PositiveIntegerField(
                        default=0, help_text="Costo en pesos chilenos"
                    ),
                ),
                ("stock_min", models.IntegerField(default=0)),
                ("ubicacion", models.CharField(blank=True, max_length=60, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
            ],
            options={
                "db_table": "producto",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("contacto", models.CharField(blank=True, max_length=120, null=True)),
                ("telefono", models.CharField(blank=True, max_length=40, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "proveedor",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
            ],
            options={
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_tipo",
                    models.CharField(
                        choices=[
                            ("FACTURA", "Factura"),
                            ("BOLETA", "Boleta"),
                            ("GUIA", "Guía de despacho"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doc_num", models.CharField(blank=True, max_length=40, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
            ],
            options={
                "db_table": "ingreso_compra",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "costo_unit",
                    models.PositiveIntegerField(
                        help_text="Costo unitario en pesos chilenos"
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.compra",
                    ),
                ),
            ],
            options={
                "db_table": "ingreso_item",
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (compra, devolución)"),
                            ("SALIDA", "Salida (venta manual, uso interno)"),
                            ("AJUSTE", "Ajuste (conteo inventario)"),
                            ("MERMA", "Merma (rotura, pérdida)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "compra_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.compraitem",
                    ),
                ),
            ],
            options={
                "db_table": "movimiento_inventario",
                "ordering": ["-fecha"],
            },
        ),
    ]
