# Generated by Django 5.1.3 on 2025-11-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="venta_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="ventas.ventaitem",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.categoria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="compraitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.proveedor"
            ),
        ),
    ]
