# Generated by Django 5.1.3 on 2025-11-16 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (compra, devolución)"),
                            ("SALIDA", "Salida (venta manual, uso interno)"),
                            ("AJUSTE", "Ajuste (conteo inventario)"),
                            ("MERMA", "Merma (rotura, pérdida)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "db_table": "movimiento_inventario",
                "ordering": ["-fecha"],
            },
        ),
    ]
