# Generated by Django 5.1.3 on 2025-11-27 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["orden", "nombre"]},
        ),
        migrations.AddField(
            model_name="categoria",
            name="activa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="actualizada",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="creada",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
        migrations.AddField(
            model_name="categoria",
            name="orden",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
