# Generated by Django 5.1.3 on 2025-11-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaProveedorProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="SKU del Proveedor",
                    ),
                ),
                (
                    "precio_costo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio de Costo"
                    ),
                ),
                (
                    "precio_sugerido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Sugerido",
                    ),
                ),
                (
                    "unidad_venta",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Unidad de Venta (e.g., Pack, Caja, Botella)",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Formato/Volumen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla Proveedor-Producto",
                "verbose_name_plural": "Plantillas Proveedor-Producto",
                "unique_together": {("proveedor", "producto")},
            },
        ),
    ]
