# Generated by Django 5.1.3 on 2025-11-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_movimientoinventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="costo",
            field=models.PositiveIntegerField(
                default=0, help_text="Costo en pesos chilenos"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.PositiveIntegerField(
                default=0, help_text="Precio de venta en pesos chilenos"
            ),
        ),
    ]
