# Generated by Django 5.1.3 on 2025-11-16 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_producto_costo_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="inventario.producto",
            ),
        ),
    ]
