# Generated by Django 5.1.3 on 2025-11-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_plantillaproveedorproducto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.proveedor",
            ),
            preserve_default=False,
        ),
    ]
