# Generated by Django 5.1.3 on 2025-11-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alter_movimientoinventario_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_tipo",
                    models.CharField(
                        choices=[
                            ("FACTURA", "Factura"),
                            ("BOLETA", "Boleta"),
                            ("GUIA", "Guía de despacho"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doc_num", models.CharField(blank=True, max_length=40, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "ingreso_compra",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("contacto", models.CharField(blank=True, max_length=120, null=True)),
                ("telefono", models.CharField(blank=True, max_length=40, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "proveedor",
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "costo_unit",
                    models.PositiveIntegerField(
                        help_text="Costo unitario en pesos chilenos"
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "db_table": "ingreso_item",
            },
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="compra_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="inventario.compraitem",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.proveedor"
            ),
        ),
    ]
