# Generated by Django 5.1.3 on 2025-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_producto_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="formato",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_de_venta",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
