# Generated by Django 5.1.3 on 2025-11-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_compra_proveedor_compraitem_and_more"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="venta_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="ventas.ventaitem",
            ),
        ),
    ]
