# Generated by Django 5.1.3 on 2025-11-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_categoria_options_categoria_activa_and_more"),
        ("inventario", "0005_producto_formato_producto_unidad_de_venta"),
    ]

    operations = []
