# Generated by Django 5.1.3 on 2025-11-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_merge_20251127_1237"),
        ("pedidos", "0003_cliente_direccion_cliente_rut_cliente_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="pedido_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="pedidos.pedidoitem",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada (compra, devolución)"),
                    ("SALIDA", "Salida (venta manual, uso interno)"),
                    ("AJUSTE", "Ajuste (conteo inventario)"),
                    ("MERMA", "Merma (rotura, pérdida)"),
                    ("RESERVA", "Reserva por pedido"),
                ],
                max_length=10,
            ),
        ),
    ]
