# Generated by Django 5.1.3 on 2025-11-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0007_movimientoinventario_pedido_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="promos/"),
                ),
                (
                    "precio_combo",
                    models.PositiveIntegerField(
                        help_text="Precio final del combo en pesos chilenos"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "mostrar_en_portada",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, se mostrará destacados en la tienda",
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
            ],
            options={
                "db_table": "promo",
                "ordering": ["-activo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="PromoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promos_items",
                        to="inventario.producto",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.promo",
                    ),
                ),
            ],
            options={
                "db_table": "promo_item",
                "unique_together": {("promo", "producto")},
            },
        ),
    ]
