# Generated by Django 5.1.3 on 2025-11-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0008_promo_promoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada (compra, devolución)"),
                    ("SALIDA", "Salida (venta manual, uso interno)"),
                    ("AJUSTE", "Ajuste (conteo inventario)"),
                    ("MERMA", "Merma (rotura, pérdida)"),
                    ("RESERVA", "Reserva por pedido"),
                    ("VENTA", "Venta"),
                ],
                max_length=10,
            ),
        ),
    ]
