# Generated by Django 5.1.3 on 2025-12-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_alter_movimientoinventario_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="activa",
            new_name="activo",
        ),
    ]
