# Generated by Django 5.1.3 on 2025-12-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0010_rename_activa_categoria_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="contiene_alcohol",
            field=models.BooleanField(default=False, verbose_name="¿Contiene alcohol?"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sku",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
