# Generated by Django 5.1.3 on 2025-12-03 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0011_producto_contiene_alcohol_alter_producto_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="archivo",
            field=models.FileField(
                blank=True,
                help_text="Sube la factura, boleta o respaldo de esta compra (PDF, imagen, etc.)",
                null=True,
                upload_to="compras_docs/",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras_registradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_inventario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
