# Generated by Django 5.1.3 on 2025-12-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_bitacoraaccion_negocio"),
        ("inventario", "0012_compra_archivo_compra_usuario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la marca",
                        null=True,
                        upload_to="marcas/",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "marca",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                help_text="Marca del producto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.marca",
            ),
        ),
    ]
