# Generated by Django 5.1.3 on 2025-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0013_marca_producto_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="es_quiebre",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el producto se quebró o rompió físicamente",
                verbose_name="¿Es quiebre?",
            ),
        ),
    ]
