# Generated by Django 5.1.3 on 2025-12-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Si está desactivado, no puede iniciar sesión en el sistema interno.",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("CAJERO", "Cajero"),
                    ("MESON", "Mesón"),
                    ("ADMIN", "Administrador"),
                ],
                default="MESON",
                help_text="Rol del usuario dentro del sistema SIPER-Pirula.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="telefono",
            field=models.CharField(
                blank=True,
                help_text="Teléfono de contacto del trabajador.",
                max_length=30,
                null=True,
            ),
        ),
    ]
