# Generated by Django 5.1.3 on 2025-12-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_perfilusuario_activo_perfilusuario_rol_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraAccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "accion",
                    models.CharField(max_length=150, verbose_name="Tipo de Acción"),
                ),
                (
                    "entidad_id",
                    models.CharField(max_length=50, verbose_name="Entidad Participe"),
                ),
                (
                    "detalles",
                    models.JSONField(default=dict, verbose_name="Detalles en Json"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Bitácora Simple",
                "verbose_name_plural": "Bitácora de Acciones Simples",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
