# Generated by Django 5.1.3 on 2025-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bitacoraaccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitacoraaccion",
            name="entidad_id",
            field=models.CharField(max_length=50, verbose_name="ID de monitor."),
        ),
    ]
