# Generated by Django 5.1.3 on 2025-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_bitacoraaccion_entidad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="banco_email",
            field=models.EmailField(
                blank=True,
                help_text="Email para notificaciones de transferencias (opcional)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="banco_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre del banco (ej: Banco de Chile, Banco Estado, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="banco_nombre_titular",
            field=models.CharField(
                blank=True,
                help_text="Nombre del titular de la cuenta",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="banco_numero_cuenta",
            field=models.CharField(
                blank=True,
                help_text="Número de cuenta bancaria",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="banco_rut_titular",
            field=models.CharField(
                blank=True,
                help_text="RUT del titular de la cuenta",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="banco_tipo_cuenta",
            field=models.CharField(
                blank=True,
                help_text="Tipo de cuenta (ej: Corriente, Vista, Ahorro)",
                max_length=20,
                null=True,
            ),
        ),
    ]
