# Generated by Django 5.1.3 on 2025-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_bitacoraaccion_entidad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitacoraaccion",
            name="nombre_modelo",
            field=models.CharField(
                default=1,
                help_text="Ej: Inventario, Venta, Usuario, Caja",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bitacoraaccion",
            name="tipo_accion",
            field=models.CharField(
                default=1,
                help_text="Ej: CREATION, EDITION, DELETION, LOGIN",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
