# Generated by Django 5.1.3 on 2025-12-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bitacoraaccion_nombre_modelo_and_more"),
        ("core", "0006_negocio_banco_email_negocio_banco_nombre_and_more"),
    ]

    operations = []
