# Generated by Django 5.1.3 on 2025-12-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_20251211_0118"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitacoraaccion",
            name="negocio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.negocio",
                verbose_name="Negocio",
            ),
        ),
    ]
