# Generated by Django 5.1.3 on 2025-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bitacoraaccion_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora hasta la cual el usuario está bloqueado por intentos fallidos.', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos de inicio de sesión fallidos consecutivos.'),
        ),
    ]
