# Generated by Django 5.1.3 on 2025-11-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_tipo",
                    models.CharField(
                        choices=[
                            ("BOLETA", "Boleta"),
                            ("FACTURA", "Factura"),
                            ("SIN_DOC", "Sin documento"),
                        ],
                        default="BOLETA",
                        max_length=10,
                    ),
                ),
                (
                    "doc_num",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número documento",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("DEBITO", "Tarjeta débito"),
                            ("CREDITO", "Tarjeta crédito"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        default="EFECTIVO",
                        max_length=15,
                    ),
                ),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("CERRADA", "Cerrada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="CERRADA",
                        max_length=10,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
            ],
            options={
                "db_table": "venta",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unit",
                    models.PositiveIntegerField(
                        help_text="Precio de venta en pesos chilenos"
                    ),
                ),
                (
                    "descuento_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Descuento porcentual sobre este ítem (0–100)",
                        max_digits=5,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "db_table": "venta_item",
            },
        ),
        migrations.CreateModel(
            name="Anulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=120)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ventas.venta"
                    ),
                ),
                (
                    "venta_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ventas.ventaitem",
                    ),
                ),
            ],
            options={
                "db_table": "anulacion",
            },
        ),
    ]
