# Generated by Django 5.1.3 on 2025-11-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0005_compra_proveedor_compraitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_tipo",
                    models.CharField(
                        choices=[
                            ("BOLETA", "Boleta"),
                            ("FACTURA", "Factura"),
                            ("SIN_DOC", "Sin documento"),
                        ],
                        default="BOLETA",
                        max_length=10,
                    ),
                ),
                (
                    "doc_num",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número documento",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("DEBITO", "Tarjeta débito"),
                            ("CREDITO", "Tarjeta crédito"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        default="EFECTIVO",
                        max_length=15,
                    ),
                ),
                ("comentario", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "venta",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unit",
                    models.PositiveIntegerField(
                        help_text="Precio de venta en pesos chilenos"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "db_table": "venta_item",
            },
        ),
    ]
