# Generated by Django 5.1.3 on 2025-11-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_cliente_direccion_cliente_rut_cliente_user"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="pedidos.pedido",
            ),
        ),
        migrations.AddField(
            model_name="ventaitem",
            name="pedido_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venta_items",
                to="pedidos.pedidoitem",
            ),
        ),
    ]
