# Generated by Django 5.1.3 on 2025-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_venta_pedido_ventaitem_pedido_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto total final de la venta (suma de subtotales de ítems).",
                max_digits=10,
            ),
        ),
    ]
