# Generated by Django 5.1.3 on 2025-12-08 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_bitacoraaccion_entidad_id"),
        ("ventas", "0003_venta_monto_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                (
                    "monto_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fondo inicial de caja en efectivo.",
                        max_digits=10,
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "monto_contado_cierre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto de efectivo contado al cierre.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("observacion_cierre", models.CharField(blank=True, max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTA", "Abierta"), ("CERRADA", "Cerrada")],
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.negocio"
                    ),
                ),
                (
                    "usuario_apertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajas_abiertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajas_cerradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "caja_turno",
            },
        ),
        migrations.CreateModel(
            name="ArqueoParcial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "monto_esperado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("monto_contado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("diferencia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observacion", models.CharField(blank=True, max_length=200)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arqueos",
                        to="ventas.cajaturno",
                    ),
                ),
            ],
            options={
                "db_table": "arqueo_parcial",
            },
        ),
        migrations.AddConstraint(
            model_name="cajaturno",
            constraint=models.UniqueConstraint(
                fields=("negocio",), name="una_caja_abierta_por_negocio"
            ),
        ),
    ]
