# Generated by Django 5.1.3 on 2025-12-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_cajaturno_arqueoparcial_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cajaturno",
            name="una_caja_abierta_por_negocio",
        ),
    ]
