# Generated by Django 5.1.3 on 2025-12-08 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_remove_cajaturno_una_caja_abierta_por_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DescuentoReglaRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("CAJERO", "Cajero"),
                            ("MESON", "Mesón"),
                            ("ADMIN", "Administrador"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "max_pct_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ej: 10.00 = 10% máximo que puede aplicar este rol a un ítem.",
                        max_digits=5,
                        verbose_name="Tope % por ítem",
                    ),
                ),
                (
                    "max_pct_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ej: 5.00 = 5% máximo sobre el total de la venta.",
                        max_digits=5,
                        verbose_name="Tope % por ticket",
                    ),
                ),
                (
                    "max_monto_item",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Monto máximo de descuento en pesos por ítem.",
                        verbose_name="Tope $ por ítem",
                    ),
                ),
                (
                    "max_monto_venta",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Monto máximo de descuento en pesos por venta.",
                        verbose_name="Tope $ por ticket",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Regla de descuento por rol",
                "verbose_name_plural": "Reglas de descuento por rol",
                "db_table": "descuento_regla_rol",
            },
        ),
        migrations.CreateModel(
            name="CodigoAutorizacionDescuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="PIN o código corto que se pedirá al cajero.",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'Código de supervisor turno tarde'.",
                        max_length=200,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opcional. Si se completa, el código no será válido después de esta fecha.",
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "max_usos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = ilimitado. Si es >0, limita la cantidad de usos.",
                    ),
                ),
                ("usos_realizados", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_descuento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de autorización de descuento",
                "verbose_name_plural": "Códigos de autorización de descuentos",
                "db_table": "codigo_autorizacion_descuento",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaDescuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=200)),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[("PORCENTAJE", "Porcentaje"), ("MONTO", "Monto fijo")],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("ITEM", "Producto / ítem"),
                            ("VENTA", "Ticket completo"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "valor_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("valor_monto", models.PositiveIntegerField(blank=True, null=True)),
                ("monto_original", models.PositiveIntegerField()),
                ("monto_final", models.PositiveIntegerField()),
                ("fecha_hora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("OK", "Aplicado correctamente"),
                            ("RECHAZADO", "Rechazado por reglas"),
                            (
                                "INTENTO_FALLIDO",
                                "Intento fallido (PIN incorrecto, etc.)",
                            ),
                        ],
                        default="OK",
                        max_length=20,
                    ),
                ),
                (
                    "terminal",
                    models.CharField(
                        blank=True,
                        help_text="Ej: nombre del equipo, IP, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "usuario_aplica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="descuentos_aplicados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_autoriza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="descuentos_autorizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias_descuentos",
                        to="ventas.venta",
                    ),
                ),
                (
                    "venta_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias_descuentos",
                        to="ventas.ventaitem",
                    ),
                ),
                (
                    "codigo_autorizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.codigoautorizaciondescuento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de descuento",
                "verbose_name_plural": "Auditoría de descuentos",
                "db_table": "auditoria_descuento",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
