# Generated by Django 5.1.3 on 2025-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_descuentoreglarol_codigoautorizaciondescuento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigoautorizaciondescuento",
            options={
                "verbose_name": "Código de autorización de descuento",
                "verbose_name_plural": "Códigos de autorización de descuento",
            },
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("OK", "Aplicado correctamente"),
                    ("RECHAZADO", "Rechazado por reglas"),
                    ("INTENTO_FALLIDO", "Intento fallido (PIN inválido, etc.)"),
                ],
                default="OK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="terminal",
            field=models.CharField(
                blank=True, help_text="Ej: equipo, IP, etc.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="codigoautorizaciondescuento",
            name="codigo",
            field=models.CharField(help_text="PIN o código corto.", max_length=20),
        ),
        migrations.AlterField(
            model_name="codigoautorizaciondescuento",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="codigoautorizaciondescuento",
            name="fecha_expiracion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="codigoautorizaciondescuento",
            name="max_usos",
            field=models.PositiveIntegerField(default=0, help_text="0 = ilimitado"),
        ),
        migrations.AlterField(
            model_name="descuentoreglarol",
            name="max_monto_item",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = sin límite por monto.",
                verbose_name="Tope $ por ítem",
            ),
        ),
        migrations.AlterField(
            model_name="descuentoreglarol",
            name="max_monto_venta",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = sin límite por monto.",
                verbose_name="Tope $ por ticket",
            ),
        ),
        migrations.AlterField(
            model_name="descuentoreglarol",
            name="max_pct_item",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ej: 10.00 = 10% máximo por ítem.",
                max_digits=5,
                verbose_name="Tope % por ítem",
            ),
        ),
        migrations.AlterField(
            model_name="descuentoreglarol",
            name="max_pct_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ej: 5.00 = 5% máximo sobre el total.",
                max_digits=5,
                verbose_name="Tope % por ticket",
            ),
        ),
    ]
