# Generated by Django 5.1.3 on 2025-12-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_alter_codigoautorizaciondescuento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditoriadescuento",
            options={"ordering": ["-fecha_hora"]},
        ),
        migrations.AlterModelOptions(
            name="codigoautorizaciondescuento",
            options={},
        ),
        migrations.AlterModelOptions(
            name="descuentoreglarol",
            options={},
        ),
        migrations.RenameField(
            model_name="codigoautorizaciondescuento",
            old_name="fecha_expiracion",
            new_name="valido_hasta",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="codigo_autorizacion",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="monto_final",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="monto_original",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="terminal",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="tipo_descuento",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="valor_monto",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="valor_porcentaje",
        ),
        migrations.RemoveField(
            model_name="auditoriadescuento",
            name="venta_item",
        ),
        migrations.RemoveField(
            model_name="codigoautorizaciondescuento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="codigoautorizaciondescuento",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="codigoautorizaciondescuento",
            name="max_usos",
        ),
        migrations.RemoveField(
            model_name="codigoautorizaciondescuento",
            name="usos_realizados",
        ),
        migrations.RemoveField(
            model_name="codigoautorizaciondescuento",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="descuentoreglarol",
            name="max_monto_item",
        ),
        migrations.RemoveField(
            model_name="descuentoreglarol",
            name="max_monto_venta",
        ),
        migrations.RemoveField(
            model_name="descuentoreglarol",
            name="max_pct_item",
        ),
        migrations.RemoveField(
            model_name="descuentoreglarol",
            name="max_pct_venta",
        ),
        migrations.AddField(
            model_name="auditoriadescuento",
            name="codigo_usado",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="auditoriadescuento",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditorias_descuento",
                to="ventas.ventaitem",
            ),
        ),
        migrations.AddField(
            model_name="auditoriadescuento",
            name="monto_descuento",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="auditoriadescuento",
            name="porc_descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="codigoautorizaciondescuento",
            name="max_pct_ticket",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tope máximo de descuento total que autoriza este código.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="codigoautorizaciondescuento",
            name="usuario_autorizador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="codigos_descuento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="descuentoreglarol",
            name="max_pct_ticket",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Máximo % de descuento sobre el ticket que puede aplicar este rol.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="fecha_hora",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="motivo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("TICKET", "Descuento sobre ticket"),
                    ("ITEM", "Descuento sobre ítem"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditoriadescuento",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditorias_descuento",
                to="ventas.venta",
            ),
        ),
        migrations.AlterField(
            model_name="codigoautorizaciondescuento",
            name="codigo",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("DEBITO", "Tarjeta débito"),
                            ("CREDITO", "Tarjeta crédito"),
                            ("TRANSFERENCIA", "Transferencia bancaria"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.PositiveIntegerField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_registra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "db_table": "pago_venta",
            },
        ),
    ]
