# Generated by Django 5.1.3 on 2025-11-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0002_initial"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelOptions(
            name="pedido",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AlterModelOptions(
            name="pedidoestadolog",
            options={"ordering": ["-fecha"]},
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="total",
            new_name="total_monto",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="core.negocio",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="pedidos.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="codigo",
            field=models.CharField(
                help_text="Código corto para mostrar al cliente (ej: ABC123).",
                max_length=16,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("RECIBIDO", "Recibido"),
                    ("PREPARANDO", "Preparando"),
                    ("LISTO", "Listo para retiro"),
                    ("RETIRADO", "Retirado"),
                    ("CANCELADO", "Cancelado"),
                    ("NO_RETIRA", "No retira"),
                ],
                default="RECIBIDO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="core.negocio",
            ),
        ),
        migrations.AlterField(
            model_name="pedidoestadolog",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estado_log",
                to="pedidos.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedidoitem",
            name="precio",
            field=models.PositiveIntegerField(
                help_text="Precio unitario en pesos chilenos."
            ),
        ),
        migrations.AlterField(
            model_name="pedidoitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedido_items",
                to="inventario.producto",
            ),
        ),
    ]
