# Generated by Django 5.1.3 on 2025-11-27 21:16

import django.db.models.deletion
import pedidos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_cliente_options_alter_pedido_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(
                blank=True,
                help_text="Dirección principal para retiro/envío",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="RUT chileno, ej: 12.345.678-9",
                max_length=12,
                null=True,
                validators=[pedidos.validators.validar_rut],
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cliente_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
