# Generated by Django 5.1.3 on 2025-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_cliente_direccion_cliente_rut_cliente_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pago",
            field=models.CharField(
                choices=[
                    ("RETIRO", "Pagar al retirar"),
                    ("WEBPAY", "Pago online Webpay"),
                ],
                default="RETIRO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("RECIBIDO", "Recibido"),
                    ("PAGADO", "Pagado"),
                    ("PREPARANDO", "Preparando"),
                    ("LISTO", "Listo para retiro"),
                    ("RETIRADO", "Retirado"),
                    ("CANCELADO", "Cancelado"),
                    ("NO_RETIRA", "No retira"),
                ],
                default="RECIBIDO",
                max_length=20,
            ),
        ),
    ]
