# Generated by Django 5.1.3 on 2025-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_pedido_forma_pago_alter_pedido_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="webpay_status",
            field=models.CharField(
                blank=True,
                help_text="Estado interno del pago Webpay (iniciado, autorizado, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="webpay_token",
            field=models.CharField(
                blank=True,
                help_text="Token de la transacción Webpay",
                max_length=255,
                null=True,
            ),
        ),
    ]
