# Generated by Django 5.1.3 on 2025-12-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_20251211_0118"),
        ("pedidos", "0005_pedido_webpay_status_pedido_webpay_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("negocio", "rut")},
        ),
    ]
