# Generated by Django 5.1.3 on 2025-12-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_alter_cliente_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together=set(),
        ),
    ]
