# Generated by Django 5.1.3 on 2025-12-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_alter_cliente_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="terminos_aceptados",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el cliente aceptó los términos al comprar.",
            ),
        ),
    ]
