# Generated by Django 5.1.3 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_pedido_terminos_aceptados"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de pago"),
                    ("PAGADO", "Pagado"),
                    ("CANCELADO", "Pago cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado de pago",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado_preparacion",
            field=models.CharField(
                choices=[
                    ("RECIBIDO", "Recibido"),
                    ("PREPARANDO", "Preparando"),
                    ("LISTO", "Listo para retiro"),
                    ("RETIRADO", "Retirado"),
                    ("CANCELADO", "Cancelado"),
                    ("NO_RETIRA", "No retira"),
                ],
                default="RECIBIDO",
                max_length=20,
                verbose_name="Estado de preparación",
            ),
        ),
        migrations.AddField(
            model_name="pedidoestadolog",
            name="tipo_estado",
            field=models.CharField(
                choices=[
                    ("PREPARACION", "Estado de preparación"),
                    ("PAGO", "Estado de pago"),
                ],
                default="PREPARACION",
                max_length=20,
                verbose_name="Tipo de estado",
            ),
        ),
    ]
